### PR TITLE
Updated cost messaging for new db/container pane

### PR DESCRIPTION
**Pull request by vchske**
Added additional text further explaining cost estimation

### CODE REVIEW

**Review by victor-meng — APPROVED** [review]

**Comment by vchske** [comment]
image
@jessica-tsui

**Comment by jessica-tsui** [comment]
Looks great, could you add one more edit? We would like to add a link to the capacity calculator (https://cosmos.azure.com/capacitycalculator/) to make sure user who needs help on estimating the amount of RU/s to be provisioned can discover that. I highlighted this in the figma file here/also in the attachment: https://www.figma.com/file/UE0tcnXYuu9ZqhVlIQPmE1ie/Hosted-Data-Explorer-v4-JT?node-id=1140%3A0 
create form

**Review by jessica-tsui — CHANGES_REQUESTED** [review]
Looks great, could you add one more edit? We would like to add a link to the capacity calculator (https://cosmos.azure.com/capacitycalculator/) to make sure user who needs help on estimating the amount of RU/s to be provisioned can discover that. I highlighted this in the figma file here/also in the attachment: https://www.figma.com/file/UE0tcnXYuu9ZqhVlIQPmE1ie/Hosted-Data-Explorer-v4-JT?node-id=1140%3A0 
create form

**Comment by vchske** [comment]
image

**Review by jessica-tsui — APPROVED** [review]

**Review by southpolesteve — APPROVED** [review]

**Pull request merged**
