### PR TITLE
complete migration of userDefinedFunctionTab in react

### PR DESCRIPTION
**Pull request by sunilyadav840**
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/860?feature.someFeatureFlagYouMightNeed=true)

Move userDefinedFunctionTab into React

https://user-images.githubusercontent.com/79906609/120791890-60fb3c80-c552-11eb-89a3-a995666ecf75.mp4

### CODE REVIEW

**Comment by southpolesteve** [comment]
@sunilyadav840 please resolve conflicts here with master

**Comment by southpolesteve** [comment]
Bug: If I create a function and then update it immediately it fails.

**Comment by sunilyadav840** [comment]
> @sunilyadav840 please resolve conflicts here with master

Resolved conflicts

**Comment by sunilyadav840** [comment]
> Bug: If I create a function and then update it immediately it fails.

@southpolesteve, Fixed. 

https://user-images.githubusercontent.com/79906609/122199546-c4bd2800-ceb7-11eb-89db-be075785e76a.mp4

**Review by southpolesteve — APPROVED** [review]

**Pull request merged**
