### PR TITLE
Switch notebook editor from Monaco back to Code Mirror

### PR DESCRIPTION
**Pull request by languy**
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/901?feature.someFeatureFlagYouMightNeed=true)

This change reverts the editor to Code Mirror

### CODE REVIEW

**Review by southpolesteve — APPROVED** [review]

**Review by gitanuj — COMMENTED** [review]
I'm looking at the Official Sample visualization notebook and all code cell heights are too big now - 
image

**Comment by languy** [comment]
There's another problem with the change. Looking at a a gallery read-only notebook and then switching back to a regular notebook makes the regular read-only.

**Comment by languy** [comment]
> There's another problem with the change. Looking at a a gallery read-only notebook and then switching back to a regular notebook makes the regular read-only.

Resolved

**Comment by languy** [comment]
> I'm looking at the Official Sample visualization notebook and all code cell heights are too big now -
> image

Resolved and fixed some other background color issues. @gitanuj  and @srinathnarayanan Can you guys take another look? Thanks!

**Review by gitanuj — APPROVED** [review]

**Pull request merged**
